# Generated by Django 4.0.1 on 2022-01-12 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_rate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange_rate',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
