# Generated by Django 4.0.1 on 2022-01-12 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_rename_project_portfolio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Portfolio',
            new_name='Project',
        ),
    ]
